/**
 * Custom label ordering per category.
 * Each entry maps a section name to an array of canonicalLabel values
 * in the desired display order. Labels not listed are appended at the end.
 */

import { normalize } from './format';

export const LABEL_ORDER = {
  'Human vocal and speech sounds': [
    'Talking or chatting',
    'Whispering',
    'Shouting',
    'Singing',
    'Humming',
    'Laughing',
    'Giggling',
    'Crying or sobbing',
    'Screaming',
    'Sighing',
    'Moaning or groaning',
    'Whistling',
    'Grunting',
  ],
  'Human respiratory and involuntary sounds': [
    'Sneezing',
    'Coughing',
    'Throat clearing',
    'Snoring',
    'Wheezing',
    'Gasping',
    'Yawning',
    'Hiccupping',
    'Panting',
    'Sniffling',
    'Breathing',
  ],
  'Human digestive, body, and contact sounds': [
    'Burping or belching',
    'Vomiting or gagging',
    'Stomach growling',
    'Swallowing or gulping',
    'Chewing or crunching',
    'Slurping',
    'Lip smacking',
    'Footsteps',
    'Hand clapping',
    'Finger snapping',
  ],
  'Baby and infant sounds': [
    'Cooing',
    'Babbling',
    'Baby crying or wailing',
    'Baby gurgling',
    'Fussing or whimpering',
    'Baby squealing',
  ],
  'Social and crowd sounds': [
    'Applause',
    'Cheering',
    'Booing',
    'Chanting',
    'Crowd murmur',
    'Crowd laughter',
  ],
  'Animal sounds': [
    'Barking',
    'Growling',
    'Meowing',
    'Purring',
    'Hissing',
    'Chirping or tweeting',
    'Screeching',
    'Buzzing insect',
    'Croaking',
    'Howling',
    'Rattlesnake rattling',
    'Chittering',
    'Rooster crowing',
    'Horse neighing',
    'Cow mooing',
  ],
  'Nature and environmental sounds': [
    'Thunder',
    'Wind howling',
    'Rain pattering',
    'Hail',
    'Avalanche rumble',
    'Earthquake rumble',
    'Wave crashing',
    'Fire crackling',
    'Rustling sound',
    'Flowing water',
    'Continuous water roar',
    'Surf or rolling waves',
    'Cracking sound',
  ],
  'Liquid and fluid sounds': [
    'Splashing',
    'Dripping',
    'Gurgling',
    'Pouring',
    'Sloshing',
    'Bubbling',
    'Spraying',
    'Gushing',
    'Trickling',
    'Sizzling sound',
    'Toilet flushing',
  ],
  'Impact and collision sounds': [
    'Thud',
    'Knock',
    'Bang',
    'Crash',
    'Clang',
    'Clatter',
    'Thump',
    'Click',
    'Crack',
    'Pop',
    'Smack or slap',
    'Slam or bang',
    'Drop impact',
    'Explosion',
    'Door opening or closing',
    'Glass shattering',
  ],
  'Friction and texture sounds': [
    'Scraping',
    'Scratching',
    'Scrunching or crinkling',
    'Squeaking',
    'Grinding',
    'Creaking',
    'Squealing',
    'Rustling or crinkling sound',
    'Abrasive rubbing',
    'Brushing or sweeping',
    'Drawer or cabinet sliding',
    'Zipping sound',
    'Scissor snipping',
  ],
  'Metallic and resonant sounds': [
    'Clanging',
    'Jangling',
    'Clinking',
    'Clanking',
    'Tinkling',
    'Ringing',
    'Rattling',
    'Ringing sound',
    'Metallic dragging',
  ],
  'Mechanical, appliance, and industrial sounds': [
    'Whirring',
    'Hum',
    'Rattle',
    'Roar',
    'Clunk',
    'Screeching sound',
    'Low-frequency hum',
    'Whooshing sound',
    'Whirring or grinding',
    'Wet grinding sound',
    'Rumbling sound',
    'Droning sound',
    'Suction motor noise',
    'Machine noise',
    'Ticking sound',
    'Electrical buzz or vibration',
  ],
  'Air and Pressure sounds': [
    'Hiss',
    'Whoosh',
    'Puff',
    'Whistling airflow',
    'Pressure-release hiss',
    'Hissing sound',
    'Deflation hiss or whoosh',
  ],
  'Electronic, alert, and interface sounds': [
    'Beep',
    'Alarm or siren',
    'Buzzer',
    'Notification tone',
    'Timer or countdown beeping',
    'Doorbell or chime tone',
    'Typing or keystrokes',
    'Interface click',
    'Tapping sound',
    'Mechanical click',
    'Switch snap or click',
    'Phone ringing tone',
    'Media playback sound',
  ],
  'Music and tonal sounds': [
    'Chime',
    'Strumming sound',
    'Drum beat',
    'Bell ringing tone',
    'Twang',
    'Piano note',
    'Flute tone',
    'Horn or trumpet',
    'Small percussion tone',
  ],
  'Food preparation and cooking sounds': [
    'Chopping',
    'Slicing',
    'Dicing',
    'Stirring',
    'Whisking',
    'Grinding or crushing',
    'Peeling',
    'Grating',
    'Kneading',
    'Boiling',
    'Frying',
    'Simmering',
    'Steaming',
    'Popping sound',
    'Crackling sound',
  ],
  'Transportation and Vehicle Sounds': [
    'Vehicle pass-by',
    'Road vehicle horn',
    'Siren',
    'Track or vehicle rumble',
    'Rail horn',
    'Brake screech',
    'Aircraft takeoff roar',
    'Engine revving',
    'Bell sound',
    'Tire squeal',
    'Rotor sound',
    'Reversing beep',
  ],
  'Construction and Tool Sounds': [
    'Hammering',
    'Drilling',
    'Sawing',
    'Sanding',
    'Jackhammer',
    'Staple gun',
    'Small metal objects dropping',
    'Ratcheting sound',
  ],
};

export const getLabelOrder = (sectionName) => {
  const key = normalize(sectionName);
  return Object.entries(LABEL_ORDER).find(([k]) => normalize(k) === key)?.[1];
};
